import { Inter } from "next/font/google";
import "./globals.css";
import { Providers } from "./redux/providers";
import { store } from "./redux/store";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Providers store={store}>
         {children} 
         {/* children means all the component and now it has passed in providers */}
        </Providers>
        </body>
    </html>
  );
}
